[package]
name = "e_macro_include"
version = "0.1.0"
edition = "2024"


[dependencies]
prettyplease = "0.2.16"
syn = { version = "2.0.51", features = ["full", "extra-traits"] }
quote = "*"
proc-macro2 = "*"

[lib]
path = "./lib.rs"
