[package]
name = "n_msg"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.148"
e_api = { path = "/r/code/rust/01_ext/99_e_api" }


[lib]
path = "./lib.rs"
